# Vivado non-project flow for checking the PULPino 150 MHz target.
#
# Run from the repository root with:
#   vivado -mode batch -source vivado_repro/run_pulpino_150mhz.tcl -tclargs -mode impl

proc fail {msg} {
  puts stderr "ERROR: $msg"
  exit 1
}

proc usage {} {
  puts "Usage: run_pulpino_150mhz.tcl ?options?"
  puts "  -part    <part>     FPGA part, default xczu9eg-ffvb1156-2"
  puts "  -period  <ns>       Clock period in ns, default 6.667"
  puts "  -top     <module>   Top module, default pulpino"
  puts "  -mode    <mode>     synth or impl, default impl"
  puts "  -out_dir <dir>      Output directory, default vivado_repro/out"
}

array set opts {
  -part    xczu9eg-ffvb1156-2
  -period  6.667
  -top     pulpino
  -mode    impl
  -out_dir vivado_repro/out
}

set i 0
while {$i < [llength $argv]} {
  set arg [lindex $argv $i]
  switch -- $arg {
    -part -
    -period -
    -top -
    -mode -
    -out_dir {
      incr i
      if {$i >= [llength $argv]} {
        usage
        fail "Missing value for $arg"
      }
      set opts($arg) [lindex $argv $i]
    }
    -help -
    --help {
      usage
      exit 0
    }
    default {
      usage
      fail "Unknown option: $arg"
    }
  }
  incr i
}

if {$opts(-mode) ni {synth impl}} {
  usage
  fail "-mode must be synth or impl, got '$opts(-mode)'"
}

if {![string is double -strict $opts(-period)] || $opts(-period) <= 0.0} {
  fail "-period must be a positive number of ns, got '$opts(-period)'"
}

proc env_int_default {name default} {
  if {[info exists ::env($name)] && $::env($name) ne ""} {
    if {![string is integer -strict $::env($name)]} {
      fail "Environment variable $name must be 0 or 1, got '$::env($name)'"
    }
    return $::env($name)
  }
  return $default
}

# These match the legacy fpga/pulpino/tcl/run.tcl defaults.
set USE_ZERO_RISCY [env_int_default USE_ZERO_RISCY 0]
set RISCY_RV32F    [env_int_default RISCY_RV32F 0]
set ZERO_RV32M     [env_int_default ZERO_RV32M 0]
set ZERO_RV32E     [env_int_default ZERO_RV32E 0]

if {$RISCY_RV32F != 0} {
  fail "RISCY_RV32F=1 needs the legacy Xilinx floating_point FMA IP. This repro script covers the default non-FPU PULPino configuration; leave RISCY_RV32F unset or 0."
}

set script_dir [file dirname [file normalize [info script]]]
set repo_root  [file normalize [file join $script_dir ..]]

proc repo_path {path} {
  return [file normalize [file join $::repo_root $path]]
}

proc normalize_repo_list {files} {
  set out {}
  foreach f $files {
    if {[file pathtype $f] eq "absolute"} {
      lappend out [file normalize $f]
    } else {
      lappend out [repo_path $f]
    }
  }
  return $out
}

proc assert_files_exist {files what} {
  set missing {}
  foreach f $files {
    if {![file exists $f]} {
      lappend missing $f
    }
  }
  if {[llength $missing] > 0} {
    set msg "Missing [llength $missing] $what file(s). First missing paths:"
    foreach f [lrange $missing 0 19] {
      append msg "\n  $f"
    }
    if {[llength $missing] > 20} {
      append msg "\n  ... plus [expr {[llength $missing] - 20}] more"
    }
    if {$what eq "HDL"} {
      append msg "\nThe Windows source tree is probably incomplete. Sync the repository RTL/IP directories, especially ips/, from a complete PULPino checkout."
    }
    fail $msg
  }
}

proc unique_ordered {items} {
  set out {}
  array set seen {}
  foreach item $items {
    set key [file normalize $item]
    if {![info exists seen($key)]} {
      set seen($key) 1
      lappend out $item
    }
  }
  return $out
}

proc split_hdl_files {files sv_var vhdl_var} {
  upvar 1 $sv_var sv_files
  upvar 1 $vhdl_var vhdl_files
  set sv_files {}
  set vhdl_files {}
  foreach f $files {
    set ext [string tolower [file extension $f]]
    if {$ext in {.vhd .vhdl}} {
      lappend vhdl_files $f
    } elseif {$ext in {.sv .v .vh}} {
      lappend sv_files $f
    } else {
      fail "Unknown HDL extension for file: $f"
    }
  }
}

proc resolve_part {part} {
  if {[llength [get_parts -quiet $part]] > 0} {
    return $part
  }

  set candidates {}
  if {![regexp -- {-[a-zA-Z]$} $part]} {
    lappend candidates "${part}-e" "${part}-i"
  }
  foreach candidate $candidates {
    if {[llength [get_parts -quiet $candidate]] > 0} {
      puts "INFO: Requested part '$part' is not installed as an exact Vivado part name; using '$candidate'."
      return $candidate
    }
  }

  set msg "Invalid part specified: '$part'."
  if {[llength $candidates] > 0} {
    append msg " Also tried: [join $candidates {, }]."
  }
  append msg " In Vivado Tcl, run: get_parts *xczu9eg*ffvb1156*"
  fail $msg
}

proc write_inferred_bram_helper {path} {
  set fh [open $path w]
  puts $fh {`timescale 1ns/1ps
// Generated by vivado_repro/run_pulpino_150mhz.tcl.
// The original FPGA flow uses a blk_mem_gen IP named xilinx_mem_8192x32.
// This helper keeps the repro flow self-contained for synthesis and timing.
module xilinx_mem_8192x32 (
  input  wire        clka,
  input  wire        rsta,
  input  wire        ena,
  input  wire [12:0] addra,
  input  wire [31:0] dina,
  output reg  [31:0] douta,
  input  wire [3:0]  wea
);
  (* ram_style = "block" *) reg [31:0] mem [0:8191];

  always @(posedge clka) begin
    if (rsta) begin
      douta <= 32'h0000_0000;
    end else if (ena) begin
      if (wea[0]) mem[addra][7:0]   <= dina[7:0];
      if (wea[1]) mem[addra][15:8]  <= dina[15:8];
      if (wea[2]) mem[addra][23:16] <= dina[23:16];
      if (wea[3]) mem[addra][31:24] <= dina[31:24];
      douta <= mem[addra];
    end
  end
endmodule
}
  close $fh
}

set xdc_path [file join $script_dir pulpino_150mhz.xdc]
set sources_path [file join $script_dir pulpino_sources.tcl]
assert_files_exist [list $xdc_path] "constraint"
assert_files_exist [list $sources_path] "source-list"

set out_dir $opts(-out_dir)
if {[file pathtype $out_dir] ne "absolute"} {
  set out_dir [repo_path $out_dir]
}
set out_dir        [file normalize $out_dir]
set reports_dir    [file join $out_dir reports]
set checkpoints_dir [file join $out_dir checkpoints]
set helpers_dir    [file join $out_dir generated]

file mkdir $out_dir
file mkdir $reports_dir
file mkdir $checkpoints_dir
file mkdir $helpers_dir

source $sources_path

if {$USE_ZERO_RISCY == 0} {
  set core_files $PULPINO_RISCV_FILES
  set core_name "ri5cy"
} else {
  set core_files $PULPINO_ZERO_RISCY_FILES
  set core_name "zero-riscy"
}

set source_files {}
foreach f [concat $PULPINO_COMMON_FILES $core_files] {
  lappend source_files [repo_path $f]
}
set source_files [unique_ordered $source_files]

set include_dirs [normalize_repo_list $PULPINO_INCLUDE_DIRS]

assert_files_exist $source_files "HDL"
assert_files_exist $include_dirs "include-directory"

set ram_helper [file join $helpers_dir xilinx_mem_8192x32_inferred.v]
write_inferred_bram_helper $ram_helper
lappend source_files $ram_helper

split_hdl_files $source_files sv_files vhdl_files

puts "=== PULPino 150 MHz timing repro ==="
puts "Repo root : $repo_root"
puts "Top       : $opts(-top)"
puts "Clock     : clk"
puts "Period    : $opts(-period) ns"
puts "Mode      : $opts(-mode)"
puts "Core      : $core_name (USE_ZERO_RISCY=$USE_ZERO_RISCY, RISCY_RV32F=$RISCY_RV32F, ZERO_RV32M=$ZERO_RV32M, ZERO_RV32E=$ZERO_RV32E)"
puts "Output    : $out_dir"
puts "SV/Verilog files: [llength $sv_files]"
puts "VHDL files      : [llength $vhdl_files]"

cd $out_dir
set resolved_part [resolve_part $opts(-part)]
puts "Part      : $resolved_part"
set_part $resolved_part

if {[llength $vhdl_files] > 0} {
  puts "Reading VHDL files..."
  read_vhdl $vhdl_files
}

puts "Reading SystemVerilog/Verilog files..."
read_verilog -sv -include_dirs $include_dirs -define {PULP_FPGA_EMUL RISCV} $sv_files

set ::PULPINO_CLOCK_PERIOD $opts(-period)
set ::PULPINO_CLOCK_PORT clk

puts "Reading constraints: $xdc_path"
read_xdc $xdc_path

puts "Running synthesis..."
synth_design \
  -top $opts(-top) \
  -part $resolved_part \
  -generic USE_ZERO_RISCY=$USE_ZERO_RISCY \
  -generic RISCY_RV32F=$RISCY_RV32F \
  -generic ZERO_RV32M=$ZERO_RV32M \
  -generic ZERO_RV32E=$ZERO_RV32E \
  -flatten_hierarchy full \
  -gated_clock_conversion on

if {[llength [get_ports -quiet clk]] != 1} {
  fail "Synthesized top '$opts(-top)' does not expose exactly one clock port named 'clk'. Check -top or pulpino_150mhz.xdc."
}
if {[llength [get_clocks -quiet clk]] != 1} {
  fail "Clock constraint 'clk' was not created. Check pulpino_150mhz.xdc."
}

check_timing -file [file join $reports_dir post_synth_check_timing.rpt]
report_timing_summary -delay_type max -report_unconstrained -check_timing_verbose -file [file join $reports_dir post_synth_timing.rpt]
report_utilization -hierarchical -file [file join $reports_dir post_synth_util.rpt]
write_checkpoint -force [file join $checkpoints_dir post_synth.dcp]

if {$opts(-mode) eq "impl"} {
  puts "Running implementation..."
  opt_design
  place_design
  route_design

  check_timing -file [file join $reports_dir post_route_check_timing.rpt]
  report_timing_summary -delay_type max -report_unconstrained -check_timing_verbose -file [file join $reports_dir post_route_timing.rpt]
  report_utilization -hierarchical -file [file join $reports_dir post_route_util.rpt]
  report_clock_utilization -file [file join $reports_dir post_route_clock_util.rpt]
  write_checkpoint -force [file join $checkpoints_dir post_route.dcp]
}

puts ""
puts "=== PULPino timing repro complete ==="
puts "Reports are in: $reports_dir"
puts "For 150 MHz, inspect post_route_timing.rpt and check WNS >= 0 and TNS = 0."
puts "If you ran -mode synth, inspect post_synth_timing.rpt first, then rerun with -mode impl for the post-route result."
